export const data = [
  {
    to: '',
    webp: '/img/pictures/user.webp',
    src: '/img/pictures/user.jpg',
    icon: '/img/pictures/chicken.svg',
    userName: 'Константинов Константин',
    sphere: 'Веб-дизайн',
    university: 'КГИК',
    status: true,
    tasks: 2,
    completedTasks: 2,
    dates: 'До 29.08.23',
  },
  {
    to: '',
    webp: '/img/pictures/user.webp',
    src: '/img/pictures/user.jpg',
    icon: '/img/pictures/chicken.svg',
    userName: 'Константинов Константин',
    sphere: 'Front End',
    university: 'КубГАУ',
    status: true,
    tasks: 22,
    completedTasks: 2,
    dates: 'До 29.08.23',
  },
  {
    to: '',
    webp: '/img/pictures/user.webp',
    src: '/img/pictures/user.jpg',
    icon: '/img/pictures/chicken.svg',
    userName: 'Константинов Константин',
    sphere: 'Back End',
    university: 'КГИК',
    status: false,
    tasks: 12,
    completedTasks: 2,
    dates: 'До 29.08.23',
  },
  {
    to: '',
    webp: '/img/pictures/user.webp',
    src: '/img/pictures/user.jpg',
    icon: '/img/pictures/chicken.svg',
    userName: 'Константинов Константин',
    sphere: 'Контент',
    university: 'КубГАУ',
    status: false,
    tasks: 21,
    completedTasks: 2,
    dates: 'До 29.08.23',
  },
]
